### ISSUE TITLE
Video player not spanning entire screen

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/web#1032]
![Untitled](https://user-images.githubusercontent.com/42515854/178314940-4e90f22d-8f10-43e8-af4e-efff2c65d7c6.png)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH tested and issue still occurs.

**Comment by GeorgeBellTMH** [comment]
Fixed?

**Comment by laurengermain** [comment]
@GeorgeBellTMH just tested this in Chrome & Safari and it still doesn't look fixed to me.
![Screen Shot 2022-09-26 at 10 07 34 AM](https://user-images.githubusercontent.com/89869101/192298237-dcc17e9c-0a66-44e7-be6c-875aca03dd3e.png)
