### ISSUE TITLE
Update pre-set preroll id for livestreams

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1034]
@GeorgeBellTMH can you please take care of this ticket this week? The new pre-roll url is:
https://youtu.be/DdKLazlFz0g

**Comment by georgevicbell** [comment]
Done

**Comment by lucastbelem** [comment]
@laurengermain it's done! You can start changing the cards each week :)

**Comment by laurengermain** [comment]
@lucastbelem awesome! Should it also be updating on themeetinghouse.com/live page (outside of Sunday mornings)? The old video is still appearing there.

**Comment by georgevicbell** [comment]
I only updated the default value...but I have now updated the mid-week default as well...it'll update shortly...
